[workspace]

members = [
    "pallas-multiplexer",
    "pallas-machines",
    "pallas-handshake",
    "pallas-blockfetch",
    "pallas-chainsync",
    "pallas-txsubmission",
    "pallas-localstate",
    "pallas-crypto",
    "pallas-alonzo",
    "pallas",
]

exclude = [
    "block-download"
]