[workspace]

members = [
    "pallas-multiplexer",
    "pallas-miniprotocols",
    "pallas-crypto",
    "pallas-primitives",
    "pallas",
    "examples/block-download",
    "examples/byron-decoder",
    "examples/submit-tx",
]
